version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always                       # always restart
    environment:
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DB}              # name of database
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}                # sample is the name of user
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}          # password for sample user
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}     # password for root user
    ports:
      - '3306:3306'                       # host port 3306 is mapper to docker port 3306
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
        mysql-db: